---
title: "Workshop: Web Scraping em R"
author: "Caio Lente + Fernando Corrêa"
date: "2018-03-10"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

<!-- ### GLOBAIS ########################################################## -->

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(comment = "#>")
library(magrittr)
```



<!-- ### ABERTURA ######################################################### -->

# Quem Somos

---
# Conteúdo

---
# Quando usar/não-usar web scraping



<!-- ### IDENTIFICAR ###################################################### -->

---
class: inverse, center, middle
# IDENTIFICAR

---
x Introdução
o Encontrar o que você quer (example web scraping website)
o Texto
o Imagem
o PDF
o Áudio



<!-- ### NAVEGAR ########################################################## -->

---
class: inverse, center, middle
# NAVEGAR

---
x HTML (estrutura básica de arquivo)
x HTML (div's, span e outros tags de conteúdo)
x HTML (atributos)
x CSS (estilizador de html)
x CSS (seletores)
o selector gadget
x outra forma de fazer seleção: XPATH
x xml2 para encontrar coisas (salvar arquivo + read_html)
x xml_find(_all)?
x Exemplo 1:
 - Inspect Texto
x Exemplo 2:
 - Inspect Imagem



<!-- ### REPLICAR ######################################################### -->

---
class: inverse, center, middle
# REPLICAR

---
x protocolo HTTP
x requisições
x exemplo de GET
x exemplo de POST
x respostas
   - o que tem na resposta
       - cookies
       - html
       - status
x Network (como que eu vejo as requests acontecendo)
x httr (como fazer requisições em R)
x httr exemplo: GET e POST
x httr o que vem na resposta
x abrir o html pra ver se deu certo



<!-- ### PARSEAR ########################################################## -->

---
class: inverse, center, middle
# PARSEAR

---

x xml2
x extraindo texto
x select tag do texto
x xml_text
x download de imagem
x tidy output
BREAK (mais ou menos por aqui começa um exemplo)
x example site
o exercícios
 1. logar numa conta (fazer o POST)
 2. baixar a página de andorra
 3. extrair os dados de andorra numa tabela



<!-- ### ITERAR ########################################################### -->

---
class: inverse, center, middle
# ITERAR

---
x baixar html
x salvar tidy output
x carefully
x walk    
o exercício
 1. baixe as páginas de todos os países
 IP BLOCK (os caras vão ter que dar ip 1)
TALVEZ OUTRO (OU O PRIMEIRO) BREAK POSSA ACONTECER AQUI



<!-- ### VALIDAR ########################################################## -->

---
class: inverse, center, middle
# VALIDAR

---
x Event validation e view state (asp)
 - TODO: PENSAR EM OUTRO EXEMPLO
x Páginas jsp
 - TODO:  PENSAR EM OUTRO EXEMPLO
x Evitar armadilhas (catpchas, etc)
 - bloqueio de IP
 - Hackear a URL (comentar)



<!-- ### MISCELÂNEA ####################################################### -->

---
class: inverse, center, middle
# MISCELÂNEA

---
x paralelização e distribuição
x Interatividade
x JS (V8, etc)
x Selenium, phantom
x RMouse



<!-- ### CAPTCHAS ######################################################### -->

---
class: inverse, center, middle
# CAPTCHAS

---
x Modelos ad hoc
x lendo a imagem no R (pacote de ler jpeg ou wtv)
x interpretando o conteudo
x filtrando com magick
x tesseract
o exercíco
 1. faça uma conta automaticamente
x Modelos keras
 - TODO: EXPLICA OU NÃO?
x decryptr


